# Production-specific configuration
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true

[imaging]
  quality = 85
  anchor = "Smart"
  resampleFilter = "Lanczos"

[caches]
  [caches.getjson]
    maxAge = "10m"
  [caches.getcsv]
    maxAge = "10m"
  [caches.images]
    maxAge = "1h"
  [caches.assets]
    maxAge = "1h" 